version: '3'

services:
  php:
    image: php:8.4-apache
    ports:
      - "80:80"
    volumes:
      - ./src/:/var/www/html/
    command: >
      bash -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"

  db:
    image: mysql:9.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studio_dusio
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:5.2.2
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
